dynamodb_region_name = "us-east-1"
dynamodb_table = "grammar-data"
origins = ["*"]
database = "mongodb"
mongodbIp = "mongodb"
mongodbPort = 27017
# database='dynamodb'
AWS_SERVER_PUBLIC_KEY = ""
AWS_SERVER_SECRET_KEY = ""
